import Sidebar from "../components/Sidebar";
import Header from "../components/Header";
import { ToastContainer, toast } from "react-toastify";

import "./globals.css";

export const metadata = {
  title: "Legal Assist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div id="webcrumbs">
          <div className="h-screen bg-white flex font-sans shadow-lg">
            <Sidebar />
            <div className="flex-1 flex flex-col h-full bg-gray-50">
              {/* Header */}
              <Header />
              {children}
              <ToastContainer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
